Header headline merge to main
Thinus01/Portfolio pull request #1
Opened 2022-10-27 15:01 UTC by Thinus01

HTML with the core structure of the mobile portfolio
CSS with visual styling for the mobile portfolio
CSS & HTML Linters added
Readme and license included

2022-10-27 15:07 UTC, Kamba56 reviewed
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a professional readme. Please add a professional readme using the template provided by microverse.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-27 15:56 UTC, HAMMAS-SALEEM reviewed
# Invalid Review Request 🔴

## Hey @Thinus01 :wave:

## Highlights :1st_place_medal:

:heavy_check_mark: Descriptive PR Title
✔️ Following Github flow
:heavy_check_mark: Following some requirements

Good job on implementing some of the requirements, But unfortunately i cannot proceed review on your pull request. there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 15:56 UTC, HAMMAS-SALEEM commented on .github/workflows/linters.yml
> +
### Your Readme File
![readme](https://user-images.githubusercontent.com/93039359/198339552-12e0aec5-1e7a-439a-aafe-9dab06f6acaf.PNG)


- [ ] You didn't add a descriptive readme file as requested by the previous reviewer. Kindly make your readme file descriptive using [microverse template](https://raw.githubusercontent.com/microverseinc/readme-template/master/README.md) 😊

2022-10-27 16:10 UTC, HAMMAS-SALEEM reviewed
# Invalid Review Request 🔴

## Hey @Thinus01 :wave:

## Highlights :1st_place_medal:

:heavy_check_mark: Descriptive PR Title
✔️ Following Github flow
:heavy_check_mark: Following some requirements

Good job on implementing some of the requirements, But unfortunately i cannot proceed review on your pull request. there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 16:10 UTC, HAMMAS-SALEEM commented on .github/workflows/linters.yml
> +
- [ ] Great work on adding a readme file but this time you have submitted this project on the wrong link in your dashboard. This project is supposed to the 2nd project but you have asked for a review from the third project link. Kindly submit this project from the second project link of this week 👍

2022-10-27 17:52 UTC, cynthiainga requested changes
Hi @Thinus01, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights

- [ ] All linters are passing ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Good commit history ✔️ 

## Required Changes ♻️

- [ ] Please kindly check the comments under the review 👇 👇 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 16:03 UTC, roshan-bajgain requested changes
Hi @Thinus01, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 20:25 UTC, PinkMoon25 approved these changes
Hi @Thinus01 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
Excellent work implementing all the required changes, your project looks professional now :clap: 

<img src="https://media3.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif"/>

## Highlights
Linters are passing :heavy_check_mark: 
Correct github flow :heavy_check_mark: 
Follows figma design :heavy_check_mark: 
Used Flexbox for layout :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 20:25 UTC, PinkMoon25 commented on style.css
> +}
[OPTIONAL] Your header is sticking to the top see :point_down: 
![image](https://user-images.githubusercontent.com/97521557/198725124-f58819ac-70df-43ef-a590-e972ea30447e.png)

I think doing this :point_down: will fix it
```
header {
  padding:  24px;
}
```

2022-10-28 20:29 UTC, merged

2022-11-10 07:21 UTC, Rana-Mudassir commented
Everything is fine. It would be better if you add some comments in your code, so it becomes more understandable for the other collaborators. 
Cheers and Happy coding!👏👏👏

2022-11-10 07:25 UTC, chigozie1803 commented
you have done great job . I think it would be good to always make sure you delete every spaces in your code, for best practice.